In [7]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

a = tf.compat.v1.Variable(5)
b = tf.compat.v1.Variable(6)

c = tf.add(a,b)
new = a.assign(c)

init_op = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init_op)
    sess.run(new)
    print(sess.run(a))
    

2026-01-26 20:24:23.844110: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2026-01-26 20:24:23.962876: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2026-01-26 20:24:23.964546: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-26 20:24:25.088841: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/hp/anaconda3/lib/python3.11/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py:37: UserWarning: A NumPy version >=1.25.2 and <2.6.0 is required for this version of SciPy (detected version 1.24.3)
  from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top

11


2026-01-26 20:24:26.389419: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled


In [14]:
sess = tf.compat.v1.Session()

sess.run(init_op)

for i in range(5):
    sess.run(new)
    print(sess.run(a))

sess.close()

11
17
23
29
35


In [ ]:
#Variables are added

In [21]:
sess = tf.compat.v1.Session()

a  = tf.constant("Hello")
b  = tf.constant("World")

In [22]:
c = tf.add(a,b)

In [25]:
print(sess.run((c)))

b'HelloWorld'


In [27]:
# Placeholder 

In [28]:
sess = tf.compat.v1.Session()

In [30]:
a = tf.compat.v1.placeholder(tf.float32)

In [31]:
b = a*2

In [34]:
result = sess.run(b, feed_dict = {a:3}) # Single dimensional
print(result)

6.0


In [35]:
result = sess.run(b, feed_dict = {a:[3,7,4]})
print(result)

[ 6. 14.  8.]


In [36]:
result = sess.run(b, feed_dict = {a:[[3,7,4], [3,6,8],[5,2,7]]})
print(result)

[[ 6. 14.  8.]
 [ 6. 12. 16.]
 [10.  4. 14.]]


In [39]:
sess.close()

In [41]:
graph = tf.compat.v1.get_default_graph()

In [42]:
graph.get_operations()

[<tf.Operation 'Variable/Initializer/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VarHandleOp>,
 <tf.Operation 'Variable/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'Variable/Assign' type=AssignVariableOp>,
 <tf.Operation 'Variable/Read/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'Variable_1/Initializer/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VarHandleOp>,
 <tf.Operation 'Variable_1/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'Variable_1/Assign' type=AssignVariableOp>,
 <tf.Operation 'Variable_1/Read/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'add/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'AssignVariableOp' type=AssignVariableOp>,
 <tf.Operation 'ReadVariableOp_1' type=ReadVariableOp>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_2/Initializer/initial_value' ty

In [43]:
a = tf.constant(10, name = 'a')

In [54]:
#operation = graph.get_operations()
#operation

In [47]:
b = tf.constant(10, name = 'b')

In [55]:
#operation = graph.get_operations()
#operation

In [50]:
c = tf.add(a,b,name = 'c')

In [56]:
#operation = graph.get_operations()
#operation

In [52]:
d = tf.multiply(a,b,name = 'd')

In [53]:
operation = graph.get_operations()
operation

[<tf.Operation 'Variable/Initializer/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VarHandleOp>,
 <tf.Operation 'Variable/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'Variable/Assign' type=AssignVariableOp>,
 <tf.Operation 'Variable/Read/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'Variable_1/Initializer/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VarHandleOp>,
 <tf.Operation 'Variable_1/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'Variable_1/Assign' type=AssignVariableOp>,
 <tf.Operation 'Variable_1/Read/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'add/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'AssignVariableOp' type=AssignVariableOp>,
 <tf.Operation 'ReadVariableOp_1' type=ReadVariableOp>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_2/Initializer/initial_value' ty

In [57]:
for i in graph.get_operations(): print(i.name)

Variable/Initializer/initial_value
Variable
Variable/IsInitialized/VarIsInitializedOp
Variable/Assign
Variable/Read/ReadVariableOp
Variable_1/Initializer/initial_value
Variable_1
Variable_1/IsInitialized/VarIsInitializedOp
Variable_1/Assign
Variable_1/Read/ReadVariableOp
ReadVariableOp
add/ReadVariableOp
add
AssignVariableOp
ReadVariableOp_1
init
Variable_2/Initializer/initial_value
Variable_2
Variable_2/IsInitialized/VarIsInitializedOp
Variable_2/Assign
Variable_2/Read/ReadVariableOp
Variable_3/Initializer/initial_value
Variable_3
Variable_3/IsInitialized/VarIsInitializedOp
Variable_3/Assign
Variable_3/Read/ReadVariableOp
Add_1/ReadVariableOp
Add_1/ReadVariableOp_1
Add_1
AssignVariableOp_1
ReadVariableOp_2
init_1
Variable_4/Initializer/initial_value
Variable_4
Variable_4/IsInitialized/VarIsInitializedOp
Variable_4/Assign
Variable_4/Read/ReadVariableOp
Variable_5/Initializer/initial_value
Variable_5
Variable_5/IsInitialized/VarIsInitializedOp
Variable_5/Assign
Variable_5/Read/ReadVaria

In [3]:
import numpy as np
import os
import sys
import tarfile
import zipfile
import tensorflow as tf
import six.moves.urllib as urllib
import matplotlib.pyplot as plt

from collections import defaultdict
from io import StringIO
from PIL import Image

In [6]:
pip install --upgrade tensorflow==1.15.0  # Last stable 1.x version

ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0, 2.18.1, 2.19.0rc0, 2.19.0, 2.19.1, 2.20.0rc0, 2.20.0)
ERROR: No matching distribution found for tensorflow==1.15.0
Note: you may need to restart the kernel to use updated packages.


In [4]:
sys.path.append("..")
from object_detection.utils import ops as utils_ops

if tf._version_<'1.4.0':
    raise ImportError("Please upgrade your tensorflow installation to v1.4. * or later!")

ModuleNotFoundError: No module named 'object_detection'

In [5]:
import tensorflow as tf
from object_detection.utils import ops as utils_ops

print("TF:", tf.__version__)
print("Object Detection utils loaded successfully")


ModuleNotFoundError: No module named 'object_detection'